### PR TITLE
Add XD meme

### PR DESCRIPTION
**Pull request by aaronryank**

### CODE REVIEW

**Comment by pavelbraginskiy** [comment]
ಠ_ಠ

**Comment by pavelbraginskiy** [comment]
ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ_ಠ

**Comment by aaronryank** [comment]
@pavelbraginskiy ಠ_ಠ

**Comment by TehFlaminTaco** [comment]
I'm reluctant to pull this, as I'm not sure it will be lastingly useful.

**Comment by aaronryank** [comment]
Ehh probably true @TehFlaminTaco

**Pull request closed without merging**
